services:
  wog:
    build:
      context: .
      dockerfile: Dockerfile-Selenium
      args:
        - CHROME_DRIVER_VERSION=${CHROME_DRIVER_VERSION}
        - WORKDIR=${WORKDIR}
        - CONTAINER_APP_PORT=${CONTAINER_APP_PORT}
    env_file:
      - .env
    volumes:
      - ./${SCORES_FILE_NAME}:${WORKDIR}/${SCORES_FILE_NAME}
    ports:
      - "${PUBLISHED_APP_PORT}:${CONTAINER_APP_PORT}"
    image: ${IMAGE_NAME}
    tty: true

