services:
  wog:
#    env_file: ".env"
    build:
      context: .
      dockerfile: Dockerfile-Selenium
    environment:
      - CHROME_DRIVER_VERSION
      - SELENIUM_HEADLESS_MODE_DISPLAY_PORT
      - INITIAL_SCORE_FOR_TESTING
      - WORKDIR
      - CONTAINER_APP_PORT
      - PUBLISHED_APP_PORT
    volumes:
      - ./{SCORES_FILE_NAME}:${WORKDIR}/${SCORES_FILE_NAME}
    ports:
      - "${PUBLISHED_APP_PORT}:${CONTAINER_APP_PORT}"
    image: ${IMAGE_NAME} ## goes to your repository on Docker Hub
    tty: true

